name: Linux build

on:
  push:
    branches: [ develop ]
    tags: 0.9.*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        qt: ['5.15.0']

    steps:
    - uses: actions/checkout@v2
      
    - name: Installing Qt framework
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}      

    - name: Running qmake
      run:  cd $GITHUB_WORKSPACE; qmake pgmodeler.pro -r PREFIX=$GITHUB_WORKSPACE/build CONFIG+=debug

    - name: Building pgModeler
      run: make -j6

    - name: Deploying pgModeler
      run: make install
     
    - name: Store the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pgModeler
          path: /home/runner/work/pgmodeler/pgmodeler/build
